source "http://rubygems.org"

gem "data_objects"
gem "data_mapper"
gem "dm-aggregates"
gem "dm-constraints"
gem "dm-core"
gem "dm-is-state_machine"
gem "dm-migrations"
gem "dm-redis-adapter"
gem 'dm-sqlite-adapter'
gem "dm-serializer"
gem "dm-pager"
gem "dm-timestamps"
gem "dm-types"
gem "dm-validations"
gem "extlib"
gem "json"
gem "rack-cache"
gem "rack-contrib"
gem "sinatra"
gem "systemu"
gem "unicorn"
gem "rest-client"
gem 'carrierwave'
gem 'i18n'
gem 'carrierwave-datamapper'
gem 'mini_magick'
